### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by CezaryH** [fernahh/imdbtr#1]
const chalk = require('chalk');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

issue on node v0.12.2

**Comment by sindresorhus** [comment]
Upgrade Node.js to latest ;)

**Comment by fernahh** [comment]
@CezaryH As told @sindresorhus, the upgrade of Node.js version should resolve your problem, ok?
