### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by captswag** [fernahh/imdbtr#5]
Using this on **Windows**, and I'm getting _SyntaxError_ every time I am using _imdbtr_ command followed by the movie name. Example

`C:\Users\Anjith Sasindran>imdbtr 'The Godfather'`

And this is the error shown

```
C:\Users\Anjith Sasindran\AppData\Roaming\npm\node_modules\imdbtr\bin\imdbtr:5
const chalk = require('chalk');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

I am using node version 1.4.28

**Comment by fernahh** [comment]
@4k3R Upgrade node to latest version. I recommend you use [nvm](https://github.com/creationix/nvm).

**Comment by captswag** [comment]
Thanks, it's working now.
